web/router.ex
defmodule CookBook.Router do
  use CookBook.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CookBook do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController do
      resources "/recipes", RecipeController
      resources "/categories", CategoryController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", CookBook do
  #   pipe_through :api
  # end
end

web/models/recipe.ex
defmodule CookBook.Recipe do
  use CookBook.Web, :model
  use Arc.Ecto.Schema

  schema "recipes" do
    field :name, :string
    field :uploadDate, Ecto.Date
    field :file, CookBook.Image.Type

    timestamps()
    belongs_to :user, CookBook.User
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :uploadDate])
    |> cast_attachments(params, [:file])
    |> validate_required([:name, :uploadDate, :file])
  end
end

web/controllers/recipe_controller.ex
defmodule CookBook.RecipeController do
  use CookBook.Web, :controller

  alias CookBook.Recipe

  plug :assign_user
  plug :authorize_user when action in [:new, :create, :update, :edit, :delete]

  def index(conn, _params) do
    recipes = Repo.all(assoc(conn.assigns[:user], :recipes))
    render(conn, "index.html", recipes: recipes)
  end

  def new(conn, _params) do
    changeset = 
      conn.assigns[:user]
      |> build_assoc(:recipes)
      |> Recipe.changeset()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"recipe" => recipe_params}) do
    IO.inspect recipe_params
    changeset = 
      conn.assigns[:user]
      |> build_assoc(:recipes)
      |> Recipe.changeset(recipe_params)

    case Repo.insert(changeset) do
      {:ok, _recipe} ->
        conn
        |> put_flash(:info, "Recipe created successfully.")
        |> redirect(to: user_recipe_path(conn, :index, conn.assigns[:user]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    recipe = Repo.get!(assoc(conn.assigns[:user], :recipes), id)
    render(conn, "show.html", recipe: recipe)
  end

  def edit(conn, %{"id" => id}) do
    recipe = Repo.get!(assoc(conn.assigns[:user], :recipes), id)
    changeset = Recipe.changeset(recipe)
    render(conn, "edit.html", recipe: recipe, changeset: changeset)
  end

  def update(conn, %{"id" => id, "recipe" => recipe_params}) do
    recipe = Repo.get!(assoc(conn.assigns[:user], :recipes), id)
    changeset = Recipe.changeset(recipe, recipe_params)

    case Repo.update(changeset) do
      {:ok, recipe} ->
        conn
        |> put_flash(:info, "Recipe updated successfully.")
        |> redirect(to: user_recipe_path(conn, :show, conn.assigns[:user], recipe))
      {:error, changeset} ->
        render(conn, "edit.html", recipe: recipe, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    recipe = Repo.get!(Recipe, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    recipe = Repo.get!(Recipe, id)

    conn
    |> put_flash(:info, "Recipe deleted successfully.")
    |> redirect(to: user_recipe_path(conn, :index, conn.assigns[:user]))
  end

  defp assign_user(conn, _opts) do
    case conn.params do
      %{"user_id" => user_id} ->
      case Repo.get(CookBook.User, user_id) do
        nil -> invalid_user(conn)
        user -> assign(conn, :user, user)
      end
      _ -> invalid_user(conn)
    end
  end

  defp invalid_user(conn) do
    conn
    |> put_flash(:error, "Invalid user!")
    |> redirect(to: page_path(conn, :index))
    |> halt
  end

  def authorize_user(conn, _opts) do
    user = get_session(conn, :current_user)
    if user && Integer.to_string(user.id) == conn.params["user_id"] do
      conn
    else
      conn
      |> put_flash(:error, "You are not authorized to modify that post!")
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end

end

web/views/recipe_view.ex
defmodule CookBook.RecipeView do
  use CookBook.Web, :view

end

web/templates/recipe/edit.html.eex
<h2>Edit recipe</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_recipe_path(@conn, :update, @user, @recipe) %>

<%= link "Back", to: user_recipe_path(@conn, @user, :index) %>

web/templates/recipe/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :file, class: "control-label" %>
    <%= file_input f, :file, class: "form-control" %>
    <%= error_tag f, :file %>
  </div>

  <div class="form-group">
    <%= label f, :uploadDate, class: "control-label" %>
    <%= date_select f, :uploadDate, class: "form-control" %>
    <%= error_tag f, :uploadDate %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/recipe/index.html.eex
<h2>Listing recipes</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Uploaddate</th>
      <th>File</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for recipe <- @recipes do %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.uploadDate %></td>

      <td class="text-right">
        <%= link "Show", to: user_recipe_path(@conn, :show, @user, recipe), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_recipe_path(@conn, :edit, @user, recipe), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_recipe_path(@conn, :delete, @user, recipe), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New recipe", to: user_recipe_path(@conn, :new, @user) %>

web/templates/recipe/new.html.eex
<h2>New recipe</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_recipe_path(@conn, :create, @user) %>

<%= link "Back", to: user_recipe_path(@conn, :index, @user) %>

web/templates/recipe/show.html.eex
<h2>Show recipe</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @recipe.name %>
  </li>

  <li>
    <strong>Uploaddate:</strong>
    <%= @recipe.uploadDate %>
  </li>

  <li>
      <%= link to: "/" <> recipe_url(@recipe, :original) do %>
      <img src="/<%= recipe_url(@recipe, :thumb) %>" />
      <% end %>
  </li>

</ul>

<%= link "Edit", to: user_recipe_path(@conn, :edit, @user, @recipe) %>
<%= link "Back", to: user_recipe_path(@conn, :index, @user) %>